-- Vygenerovano skriptem tools/extract_services.py z msginfo.html.
-- Spustte v Supabase SQL Editoru az PO souboru supabase-services.sql.
-- Pocet sluzeb: 31

insert into public.services (category, name, slug, description, duration_minutes, price_czk, image_path, image_alt, reservio_url, recommended, badge_text, sort_order) values
  ('klasicke', 'Záda a šíje', 'zada a sije klasicka masaz', 'Klasická cílená masáž pro uvolnění nejvíce přetížených oblastí.', 50, 800, 'galerie/masaze/kmz.webp', 'Klasická masáž zad a šíje', 'https://aura-michaell-massage.reservio.com/services/8cc1ae74-f248-41f5-b532-87a75d527a49', true, 'Doporučujeme', 10),
  ('klasicke', 'Záda, šíje, dolní končetiny', 'zada sije dolni koncetiny zepredu zezadu', 'Komplexní celotělovější varianta pro hloubkové uvolnění.', 120, 1600, 'galerie/masaze/kmzsdkp.webp', 'Klasická masáž zad, šíje a dolních končetin', 'https://aura-michaell-massage.reservio.com/services/cfbda387-3f4c-4ddb-bf89-9f553735ee35', false, null, 20),
  ('klasicke', 'Dolní končetiny zepředu i zezadu', 'dolni koncetiny zepredu zezadu klasicka', 'Skvělá volba při unavených nohou a dlouhém stání.', 60, 850, 'galerie/masaze/kmdkzp.webp', 'Klasická masáž dolních končetin zepředu i zezadu', 'https://aura-michaell-massage.reservio.com/services/5fc39bb3-7e02-4078-8a4f-857194b828a4', false, null, 30),
  ('klasicke', 'Dolní končetiny zezadu', 'dolni koncetiny zezadu klasicka', 'Kratší varianta zaměřená na zadní stranu nohou.', 30, 400, 'galerie/masaze/kmdkz.webp', 'Klasická masáž dolních končetin zezadu', 'https://aura-michaell-massage.reservio.com/services/cdd9d157-6b1c-46a9-b2a6-9f854ff60cb9', false, null, 40),
  ('klasicke', 'Dolní končetiny zepředu', 'dolni koncetiny zepredu klasicka', 'Jemná, ale efektivní péče o přední stranu nohou.', 30, 400, 'galerie/masaze/kmdkp.webp', 'Klasická masáž dolních končetin zepředu', 'https://aura-michaell-massage.reservio.com/services/e114d069-2856-4e8b-8448-455734d0edae', false, null, 50),
  ('klasicke', 'Horní končetiny', 'horni koncetiny klasicka', 'Úleva předloktí, pažím a ramenům po zátěži i práci.', 30, 500, 'galerie/masaze/kmhk.webp', 'Klasická masáž horních končetin', 'https://aura-michaell-massage.reservio.com/services/cfc019ba-80cc-4efd-a9f1-0183bde08544', false, null, 60),
  ('sportovni', 'Záda a šíje', 'sportovni zada sije', 'Silnější technika pro přetížené trapézy a mezilopatkovou oblast.', 50, 800, 'galerie/masaze/smzs.webp', 'Sportovní masáž zad a šíje', 'https://aura-michaell-massage.reservio.com/services/cc7f914d-b398-4a1f-bb89-9c20d39eafd0', true, 'Top volba', 10),
  ('sportovni', 'Šíje', 'sportovni sije', 'Rychlá lokální pomoc při napětí v oblasti krku.', 15, 200, 'galerie/masaze/sms.webp', 'Sportovní masáž šíje', 'https://aura-michaell-massage.reservio.com/services/c9febe66-1ee5-497a-bc5c-e087dd1d9e07', false, null, 20),
  ('sportovni', 'Záda, šíje, dolní končetiny', 'sportovni zada sije dolni koncetiny', 'Intenzivní celotělesná varianta pro aktivní klienty.', 110, 1600, 'galerie/masaze/smzsdkzp.webp', 'Sportovní masáž zad, šíje a dolních končetin', 'https://aura-michaell-massage.reservio.com/services/fb4065e8-74fe-47c6-b6fe-10246772fca6', false, null, 30),
  ('sportovni', 'Dolní končetiny a hýždě', 'sportovni dolni koncetiny hyzde', 'Cílené uvolnění nohou po běhu, kole nebo dlouhém stání.', 90, 850, 'galerie/masaze/smdkzp.webp', 'Sportovní masáž dolních končetin a hýždí', 'https://aura-michaell-massage.reservio.com/services/11af849a-d558-4a49-84da-691967541069', false, null, 40),
  ('sportovni', 'Horní končetiny a rameno', 'sportovni horni koncetiny rameno', 'Odlehčí přetížení paží a ramen po sportu i práci.', 40, 400, 'galerie/masaze/smhkr.webp', 'Sportovní masáž horních končetin a ramene', 'https://aura-michaell-massage.reservio.com/services/1b6bdcdd-3390-4be2-94fc-10db7507a18f', false, null, 50),
  ('sportovni', 'Dolní končetiny zepředu', 'sportovni dolni koncetiny zepredu', 'Aktivační i regenerační varianta pro přední svalové řetězce.', 30, 450, 'galerie/masaze/smdkp.webp', 'Sportovní masáž dolních končetin zepředu', 'https://aura-michaell-massage.reservio.com/services/eaed703f-134d-46e5-a8a2-802c074081e3', false, null, 60),
  ('sportovni', 'Dolní končetiny zezadu', 'sportovni dolni koncetiny zezadu', 'Cílený zásah na hamstringy, lýtka a svalové trigger body.', 30, 450, 'galerie/masaze/smdkz.webp', 'Sportovní masáž dolních končetin zezadu', 'https://aura-michaell-massage.reservio.com/services/91870220-0ec5-43c4-8c45-15478ce014ee', false, null, 70),
  ('zabaly', 'Parafínový zábal rukou', 'parafinovy zabal rukou', 'Prohřátí, hydratace a péče o klouby i pokožku rukou.', 30, 350, 'galerie/masaze/pzr.webp', 'Parafínový zábal rukou', 'https://aura-michaell-massage.reservio.com/services/851b4828-53b3-40b0-a4f9-f0aaf3cbe38e', false, null, 10),
  ('zabaly', 'Parafínový zábal nohou', 'parafinovy zabal nohou', 'Zmírnění únavy a příjemné hloubkové prohřátí chodidel.', 30, 350, 'galerie/masaze/pzn.webp', 'Parafínový zábal nohou', 'https://aura-michaell-massage.reservio.com/services/c23df20e-7152-4dc0-aa84-16d9b973eb1a', false, null, 20),
  ('zabaly', 'Rašelinový zábal zad', 'raselinovy zabal zad', 'Tepelná terapie pro bedra a oblast mezi lopatkami.', 35, 350, 'galerie/masaze/rasz.webp', 'Rašelinový zábal zad', 'https://aura-michaell-massage.reservio.com/services/eb45b07c-c18d-4518-982a-720ab1c5f195', false, null, 30),
  ('zabaly', 'Rašelinový zábal šíje', 'raselinovy zabal sije', 'Cílené uvolnění krční oblasti a trapézových svalů.', 35, 350, 'galerie/masaze/rass.webp', 'Rašelinový zábal šíje', 'https://aura-michaell-massage.reservio.com/services/c0715d98-03ea-40e4-a812-2b3650c85ef9', false, null, 40),
  ('scratch', 'Šepot doteku', 'sepot doteku', 'Pomalý rituál hlazení, škrábání a zklidnění celé nervové soustavy.', 30, 400, 'galerie/masaze/vd.webp', 'Šepot doteku', 'https://aura-michaell-massage.reservio.com/services/947a02c2-394e-4ec5-b067-8b36631e624f', true, 'Nejjemnější péče', 10),
  ('vedomy', 'Vědomý dotek', 'vedomy dotek', 'Hluboké zpomalení, vědomá práce s tělem a návrat k vnitřnímu klidu.', 90, 2500, 'galerie/masaze/vd2.webp', 'Vědomý dotek', 'https://aura-michaell-massage.reservio.com/services/5d8755a6-e69d-4497-8286-1898380ff92e', false, null, 10),
  ('vedomy', 'Vedená hluboká meditace', 'vedena hluboka meditace', 'Individuálně vedená mluvená meditace pro zklidnění nervového systému a snížení stresu.', 60, 690, 'galerie/masaze/vhm.webp', 'Vedená hluboká meditace', 'https://aura-michaell-massage.reservio.com/services/dd854084-5247-49da-b097-b1b0a43fba13', false, null, 20),
  ('motyli', 'Baby motýlí dotek', 'baby motyli dotek', 'Láskyplný rituál vědomého doteku pro miminka a jejich rodiče.', 60, 890, 'galerie/masaze/bmd.webp', 'Baby motýlí dotek', 'https://aura-michaell-massage.reservio.com/services/f807fbbd-29bb-4f24-9646-7f2aa02e4d7b', false, null, 10),
  ('motyli', 'Motýlí dotek - záda', 'motyli dotek zada', 'Jemná, respektující masáž zad pro dětské uvolnění a zklidnění.', 30, 350, 'galerie/masaze/mdz.webp', 'Motýlí dotek - záda', 'https://aura-michaell-massage.reservio.com/services/6096c4ac-fad9-4012-8dd6-63335a6063ae', false, null, 20),
  ('motyli', 'Motýlí dotek - dolní končetiny', 'motyli dotek dolni koncetiny', 'Citlivá péče o nohy, která podporuje uvolnění těla a celkovou pohodu dítěte.', 30, 300, 'galerie/masaze/mddk.webp', 'Motýlí dotek - dolní končetiny', 'https://aura-michaell-massage.reservio.com/services/72ecfbf6-812a-43b0-9d59-895eb25b9b0c', false, null, 30),
  ('bankovani', 'Baňkování s masáží', 'bankovani s masazi', '35 minut masáže a 25 minut baňkování.', 60, 900, 'galerie/masaze/banky.webp', 'Baňkování s masáží', 'https://aura-michaell-massage.reservio.com/services/6be9b101-bbf4-40af-baf2-1f3fa1195b03', false, null, 10),
  ('bankovani', 'Baňkování s masáží 90 min.', 'bankovani s masazi 90', '60 minut masáže a 30 minut baňkování.', 90, 1050, 'galerie/masaze/banky2.webp', 'Baňkování s masáží 90 min.', 'https://aura-michaell-massage.reservio.com/services/19058041-2dfd-4b66-b48b-082c899df135', false, null, 20),
  ('fullbody', 'Signature Full Body Ritual 180 min.', 'signature full body ritual', 'Dopřejte si tři hodiny hluboké relaxace a komplexní péče o celé tělo.', 180, 3200, 'galerie/masaze/sfbr.webp', 'Signature Full Body Ritual 180 min.', 'https://aura-michaell-massage.reservio.com/services/3ae7f543-4de3-40e2-8c0d-82f005dd1a34', false, null, 10),
  ('tarot', 'Výklad tarotu', 'vyklad tarotu', 'Výklad karet v bezpečné a respektující atmosféře.', 60, 500, 'galerie/masaze/vt.webp', 'Výklad tarotu', 'https://aura-michaell-massage.reservio.com/services/324e67c7-de15-455b-bd63-b9e04d0d4de6', false, null, 10),
  ('ostatni', 'Lávové kameny', 'lavove kameny', 'Hřejivé kameny zmírňují stres, ztuhlost a podporují tok energie.', 60, 900, 'galerie/masaze/lk.webp', 'Lávové kameny', 'https://aura-michaell-massage.reservio.com/services/40f64f4e-c7d7-4656-bcaa-9c5f2ab7b188', false, null, 10),
  ('ostatni', 'Antistresová masáž hlavy', 'antistresova masaz hlavy', 'Relaxační technika pro uvolnění napětí hlavy, šíje a temene.', 30, 400, 'galerie/masaze/amh.webp', 'Antistresová masáž hlavy', 'https://aura-michaell-massage.reservio.com/services/322423c0-bdda-49e4-bb01-dc289824e725', false, null, 20),
  ('ostatni', 'Relaxační masáž obličeje a dekoltu', 'relaxacni masaz obliceje dekoltu', 'Jemná technika pro zklidnění mimiky, osvěžení pleti a odpočinek.', 30, 400, 'galerie/masaze/rmod.webp', 'Relaxační masáž obličeje a dekoltu', 'https://aura-michaell-massage.reservio.com/services/789051db-4d63-4b75-8e9a-bdd1e25814e3', false, null, 30),
  ('ostatni', 'Rituál šťastná maminka', 'ritual stastna maminka', 'Jemná péče pro těhotné, maminky i každou ženu.', 50, 800, 'galerie/masaze/rsm.webp', 'Rituál šťastná maminka', 'https://aura-michaell-massage.reservio.com/services/11e33b11-2e8f-4f07-af05-f4a830cf2a20', true, 'Oblíbená péče', 40);

